Repository allure-framework/allure-php-api, pull requests merged in 2020-03, with the labels that each got.

#55 Add actions
  .github/release-drafter.yml
  .github/workflows/build.yml
  .github/workflows/draft-release.yml
  composer.json
Labels: type:improvement

#56 Build on master
  .github/workflows/build.yml
Labels: type:improvement

#57 Add custom labels
  src/Yandex/Allure/Adapter/Annotation/AllureId.php
  src/Yandex/Allure/Adapter/Annotation/AnnotationManager.php
  src/Yandex/Allure/Adapter/Annotation/Label.php
  src/Yandex/Allure/Adapter/Annotation/Labels.php
  src/Yandex/Allure/Adapter/Model/Label.php
  src/Yandex/Allure/Adapter/Model/LabelType.php
  test/Yandex/Allure/Adapter/Annotation/AnnotationManagerTest.php
  test/Yandex/Allure/Adapter/Annotation/Fixtures/ExampleTestSuite.php
Labels: type:new feature

#59 Add epic support
  src/Yandex/Allure/Adapter/Annotation/AnnotationManager.php
  src/Yandex/Allure/Adapter/Annotation/Epics.php
  src/Yandex/Allure/Adapter/Model/Label.php
  src/Yandex/Allure/Adapter/Model/LabelType.php
  test/Yandex/Allure/Adapter/Annotation/AnnotationManagerTest.php
  test/Yandex/Allure/Adapter/Annotation/Fixtures/ExampleTestSuite.php
Labels: type:improvement

#60 ramsey/uuid 4.0.0 supported
  composer.json
  composer.lock
Labels: type:dependencies

#58 Migrate from single value to multi-value in Label annotation
  src/Yandex/Allure/Adapter/Annotation/AnnotationManager.php
  src/Yandex/Allure/Adapter/Annotation/Label.php
  test/Yandex/Allure/Adapter/Annotation/AnnotationManagerTest.php
  test/Yandex/Allure/Adapter/Annotation/Fixtures/ExampleTestSuite.php
Labels: type:improvement
